# Default style file for nitpick
# https://raw.githubusercontent.com/andreoliwa/nitpick/v0.22.2/nitpick-style.toml

[nitpick]
minimum_version = "0.23.1"

[nitpick.styles]
include = [
    "styles/absent-files",
    "styles/pre-commit/main",
    "styles/pre-commit/general",
    "styles/pre-commit/python",
    "styles/pre-commit/bash",
    "styles/black",
    "styles/mypy",
    "styles/pytest",
    "styles/orchestrator-core",
    "styles/mypy-pydantic",
]
