[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus
          - --keep-runtime-typing
"""
