[["pyproject.toml".contains]]
line = "more-itertools~=8.7.0"
[["pyproject.toml".contains]]
line = "structlog~=20.2.0"

[["pyproject.toml".contains]]
line = "-r base.txt"
[["pyproject.toml".contains]]
line = "black"
[["pyproject.toml".contains]]
line = "flake8"
[["pyproject.toml".contains]]
line = "flake8-bandit"
[["pyproject.toml".contains]]
line = "flake8-bugbear"
[["pyproject.toml".contains]]
line = "flake8-comprehensions"
[["pyproject.toml".contains]]
line = "flake8-docstrings"
[["pyproject.toml".contains]]
line = "flake8-junit-report"
[["pyproject.toml".contains]]
line = "flake8-logging-format"
[["pyproject.toml".contains]]
line = "flake8-pep3101"
[["pyproject.toml".contains]]
line = "flake8-print"
[["pyproject.toml".contains]]
line = "flake8-rst"
[["pyproject.toml".contains]]
line = "flake8-rst-docstrings"
[["pyproject.toml".contains]]
line = "flake8-tidy-imports"
[["pyproject.toml".contains]]
line = "isort"
# [["pyproject.toml".contains]]
# line = "mypy"
[["pyproject.toml".contains]]
line = "pytest"
[["pyproject.toml".contains]]
line = "pytest-cov"
[["pyproject.toml".contains]]
line = "pytest-xdist"
[["pyproject.toml".contains]]
line = "pre-commit"